import type { SandboxNetworkPolicy } from "eve/sandbox";
import type { SandboxBackendKind } from "./backend-kind";
import { SANDBOX_DEFAULT_IMAGE } from "./image";
import { DEFAULT_UNTRUSTED_NETWORK_POLICY, toDockerNetworkPolicy } from "./network-policy";

export interface GenerateSandboxModuleOptions {
  /** Backend the generated module pins. */
  readonly backendKind: SandboxBackendKind;
  /** Egress policy. Defaults to {@link DEFAULT_UNTRUSTED_NETWORK_POLICY}. */
  readonly networkPolicy?: SandboxNetworkPolicy;
  /** OCI image for the microVM. Defaults to {@link SANDBOX_DEFAULT_IMAGE}. */
  readonly image?: string;
}

/** Backend factory name + subpath import for each kind (real eve exports). */
const BACKEND_IMPORT: Record<SandboxBackendKind, { readonly name: string; readonly path: string }> = {
  microsandbox: { name: "microsandbox", path: "eve/sandbox/microsandbox" },
  docker: { name: "docker", path: "eve/sandbox/docker" },
  justbash: { name: "justbash", path: "eve/sandbox/just-bash" },
};

/**
 * Renders the `backend: () => <factory>(...)` expression for a kind, matching
 * the per-backend network-policy support (see {@link createSandboxBackend}).
 */
const renderBackendCall = (
  kind: SandboxBackendKind,
  policy: SandboxNetworkPolicy,
  image: string,
): string => {
  const literal = (value: unknown): string => JSON.stringify(value, null, 2);
  switch (kind) {
    case "microsandbox":
      return `microsandbox({ image: ${JSON.stringify(image)}, networkPolicy: ${literal(policy)} })`;
    case "docker":
      // Docker only supports the coarse "allow-all" | "deny-all" form.
      return `docker({ networkPolicy: ${literal(toDockerNetworkPolicy(policy))} })`;
    case "justbash":
      // just-bash has no network stack, so no policy is applied.
      return `justbash()`;
  }
};

/**
 * Returns the TypeScript SOURCE TEXT for a materialized eve agent's
 * `agent/sandbox.ts`. The generated file imports only from `eve/...` (never
 * from `@xagents/sandbox`) so materialized projects don't take a runtime
 * dependency on this package, and default-exports the sandbox definition —
 * eve reads the definition from the default export of the path-derived module.
 */
export const generateSandboxModuleSource = (
  opts: GenerateSandboxModuleOptions,
): string => {
  const policy = opts.networkPolicy ?? DEFAULT_UNTRUSTED_NETWORK_POLICY;
  const image = opts.image ?? SANDBOX_DEFAULT_IMAGE;
  const { name, path } = BACKEND_IMPORT[opts.backendKind];
  return `// Generated by @xagents/sandbox — do not edit by hand.
// Sandbox backend for this materialized eve agent.
import { defineSandbox } from "eve/sandbox";
import { ${name} } from "${path}";

export default defineSandbox({
  backend: () => ${renderBackendCall(opts.backendKind, policy, image)},
});
`;
};
