import type { ReasoningEffort } from "@xagents/core";

/**
 * Provider id -> how to import its AI SDK model factory in a materialized
 * `agent/agent.ts`. Only DeepSeek is wired for the MVP; add rows to support
 * more providers (the factory must accept a model id string).
 */
const PROVIDER_MODEL_IMPORT: Record<string, { readonly module: string; readonly factory: string }> = {
  deepseek: { module: "@ai-sdk/deepseek", factory: "deepseek" },
};

export const isSupportedProvider = (provider: string): boolean =>
  provider in PROVIDER_MODEL_IMPORT;

/** Source text for a materialized agent's `agent/agent.ts`. */
export const generateAgentModuleSource = (args: {
  readonly provider: string;
  readonly modelId: string;
  readonly reasoning: ReasoningEffort;
}): string => {
  const entry = PROVIDER_MODEL_IMPORT[args.provider];
  if (entry === undefined) {
    throw new Error(`unsupported model provider: ${args.provider}`);
  }
  // Only emit `reasoning` when it diverges from the provider default, so models
  // that don't expose a thinking control aren't handed an unsupported option.
  const reasoningLine =
    args.reasoning === "provider-default"
      ? ""
      : `\n  reasoning: ${JSON.stringify(args.reasoning)},`;
  return `// Generated by @xagents/eve-runtime — do not edit by hand.
import { defineAgent } from "eve";
import { ${entry.factory} } from "${entry.module}";

export default defineAgent({
  model: ${entry.factory}(${JSON.stringify(args.modelId)}),${reasoningLine}
});
`;
};

/**
 * Source text for a materialized agent's `agent/tools/kb_search.ts`. The tool
 * runs inside the eve host (a separate process) and calls back into the
 * platform server, so the DB stays owned by one process. The internal endpoint
 * resolves the agent's attached knowledgebases and runs BM25 retrieval.
 */
export const generateKbSearchToolSource = (args: {
  readonly internalUrl: string;
  readonly agentId: string;
}): string => {
  const endpoint = `${args.internalUrl.replace(/\/+$/, "")}/internal/agents/${args.agentId}/kb-search`;
  return `// Generated by @xagents/eve-runtime — do not edit by hand.
import { defineTool } from "eve/tools";
import { z } from "zod";

const ENDPOINT = ${JSON.stringify(endpoint)};

export default defineTool({
  description:
    "Search the agent's attached knowledgebases for relevant passages. " +
    "Call this before answering questions that may rely on the agent's " +
    "documents, and cite the returned 'citation' values in your answer.",
  inputSchema: z.object({
    query: z.string().min(1).describe("Natural-language search query"),
    limit: z.number().int().min(1).max(10).default(5),
  }),
  async execute({ query, limit }) {
    const res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ query, limit }),
    });
    if (!res.ok) {
      return { hits: [], error: \`knowledgebase search failed (\${res.status})\` };
    }
    return (await res.json()) as { hits: unknown[] };
  },
});
`;
};

/** Source text for the materialized project's root `package.json`. */
export const generateProjectPackageJson = (agentSlug: string): string =>
  `${JSON.stringify(
    {
      name: `xagents-agent-${agentSlug}`,
      type: "module",
      private: true,
    },
    null,
    2,
  )}\n`;
