import { type ProviderCodegen, type ReasoningEffort, ADAPTERS, providerSecretEnvVar } from "@xagents/core";

/**
 * Code generation for a materialized agent's `agent/agent.ts`. The provider is
 * built from an admin-managed adapter descriptor: the SDK import and factory come
 * from `@xagents/core`'s `ADAPTERS`, non-secret settings (base URL, region…) are
 * baked in, and secrets are read at runtime from env vars — NEVER written to disk
 * — using the same `providerSecretEnvVar` naming the server injects them under.
 */

export const isSupportedAdapterKind = (kind: string): boolean => kind in ADAPTERS;

/** `process.env.XAGENTS_PROVIDER_SECRET_<FIELD>` — where the server puts the key. */
const envExpr = (field: string): string => `process.env.${providerSecretEnvVar(field)}`;

/** The `import` line + `createX({...})` expression for one provider's adapter. */
const providerConstruction = (cg: ProviderCodegen): { readonly imports: string; readonly expr: string } => {
  const adapter = ADAPTERS[cg.adapterKind];
  const imports = `import { ${adapter.factory} } from "${adapter.sdkModule}";`;
  const setting = (k: string): string => JSON.stringify(cg.settings[k] ?? "");
  switch (cg.adapterKind) {
    case "deepseek":
    case "anthropic":
    case "google":
      return { imports, expr: `${adapter.factory}({ apiKey: ${envExpr("apiKey")} })` };
    case "openai-compatible":
      return {
        imports,
        expr: `${adapter.factory}({ name: ${JSON.stringify(cg.providerId)}, baseURL: ${setting("baseURL")}, apiKey: ${envExpr("apiKey")} })`,
      };
    case "azure":
      return {
        imports,
        expr: `${adapter.factory}({ resourceName: ${setting("resourceName")}, apiKey: ${envExpr("apiKey")}${
          cg.settings.apiVersion !== undefined && cg.settings.apiVersion.length > 0
            ? `, apiVersion: ${setting("apiVersion")}`
            : ""
        } })`,
      };
    case "google-vertex":
      return {
        imports,
        expr: `${adapter.factory}({ project: ${setting("project")}, location: ${setting("location")}, googleAuthOptions: { credentials: JSON.parse(${envExpr("credentialsJson")} ?? "{}") } })`,
      };
  }
};

/**
 * Source text for a materialized agent's `agent/agent.ts`.
 *
 * The model is authored as an eve *dynamic* model rather than a static one, to
 * support per-chat model hot-swap. On every step eve calls the resolver, which
 * asks the platform (over the same internal callback channel the `kb_search`
 * tool uses) for this session's active model — the chat's override, or this
 * agent's default. The resolver returns a provider-built `LanguageModel`, which
 * `step.started` scope allows (session/turn scope would require a serializable
 * gateway id, incompatible with our direct-provider SDK + keys). Because the
 * running eve session is untouched, swapping models preserves conversation
 * history and takes effect from the next turn. `fallback` is the agent's default
 * model, used until the resolver first answers (e.g. the very first turn).
 */
export const generateAgentModuleSource = (args: {
  readonly provider: ProviderCodegen;
  readonly modelId: string;
  readonly reasoning: ReasoningEffort;
  /** Base URL of the platform server the model resolver calls back into. */
  readonly internalUrl: string;
  readonly agentId: string;
}): string => {
  if (!isSupportedAdapterKind(args.provider.adapterKind)) {
    throw new Error(`unsupported adapter kind: ${args.provider.adapterKind}`);
  }
  const { imports, expr } = providerConstruction(args.provider);
  const endpoint = `${args.internalUrl.replace(/\/+$/, "")}/internal/agents/${args.agentId}/turn-model`;
  // Only emit `reasoning` when it diverges from the provider default, so models
  // that don't expose a thinking control aren't handed an unsupported option.
  const reasoningLine =
    args.reasoning === "provider-default" ? "" : `\n  reasoning: ${JSON.stringify(args.reasoning)},`;
  return `// Generated by @xagents/eve-runtime — do not edit by hand.
import { defineAgent, defineDynamic } from "eve";
${imports}

const provider = ${expr};
const DEFAULT_MODEL = ${JSON.stringify(args.modelId)};
const MODEL_ENDPOINT = ${JSON.stringify(endpoint)};

// Resolve this chat's active model (its hot-swap override, or DEFAULT_MODEL).
// Any failure falls back to the default so a turn never breaks on the lookup.
const resolveModelId = async (sessionId) => {
  try {
    const res = await fetch(MODEL_ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ sessionId }),
    });
    if (!res.ok) return DEFAULT_MODEL;
    const body = await res.json();
    return typeof body?.modelId === "string" && body.modelId.length > 0 ? body.modelId : DEFAULT_MODEL;
  } catch {
    return DEFAULT_MODEL;
  }
};

export default defineAgent({
  model: defineDynamic({
    fallback: provider(DEFAULT_MODEL),
    events: {
      "step.started": async (_event, ctx) => provider(await resolveModelId(ctx.session.id)),
    },
  }),${reasoningLine}
});
`;
};

/**
 * Source text for a materialized agent's `agent/tools/kb_search.ts`. The tool
 * runs inside the eve host (a separate process) and calls back into the
 * platform server, so the DB stays owned by one process. The internal endpoint
 * resolves the agent's attached knowledgebases and runs BM25 retrieval.
 */
export const generateKbSearchToolSource = (args: {
  readonly internalUrl: string;
  readonly agentId: string;
}): string => {
  const endpoint = `${args.internalUrl.replace(/\/+$/, "")}/internal/agents/${args.agentId}/kb-search`;
  return `// Generated by @xagents/eve-runtime — do not edit by hand.
import { defineTool } from "eve/tools";
import { z } from "zod";

const ENDPOINT = ${JSON.stringify(endpoint)};

export default defineTool({
  description:
    "Search the agent's attached knowledgebases for relevant passages. " +
    "Call this before answering questions that may rely on the agent's " +
    "documents, and cite the returned 'citation' values in your answer.",
  inputSchema: z.object({
    query: z.string().min(1).describe("Natural-language search query"),
    limit: z.number().int().min(1).max(10).default(5),
  }),
  async execute({ query, limit }) {
    const res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ query, limit }),
    });
    if (!res.ok) {
      return { hits: [], error: \`knowledgebase search failed (\${res.status})\` };
    }
    return (await res.json()) as { hits: unknown[] };
  },
});
`;
};

/** Source text for the materialized project's root `package.json`. */
export const generateProjectPackageJson = (agentSlug: string): string =>
  `${JSON.stringify(
    {
      name: `xagents-agent-${agentSlug}`,
      type: "module",
      private: true,
    },
    null,
    2,
  )}\n`;
